### ISSUE TITLE
Bugged Colors in built executables

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine-ldjam46#1]
For a long time, the Windows executables of games built with LITIengine have suffered from strangely aberrant colors in whatever Screen is rendered first. 

Will provide a screenshot comparison later.

**Comment by steffen-wilke** [comment]
Apparently, it seems like the jre we used for bundling was somehow corrupt. I replaced the entire folder with my locally installed `jre1.8.0_211`. This might have to do with the architecture or with some other missing binaries.

broken JRE version info:
```
JAVA_VERSION="1.8.0_151"
OS_NAME="Windows"
OS_VERSION="5.1"
OS_ARCH="i586"
...
```

worker JRE version info:
```
JAVA_VERSION="1.8.0_211"
OS_NAME="Windows"
OS_VERSION="5.2"
OS_ARCH="amd64"
```
